// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 



module matrix33 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        firstMatrix_address0,
        firstMatrix_ce0,
        firstMatrix_q0,
        firstMatrix_address1,
        firstMatrix_ce1,
        firstMatrix_q1,
        secondMatrix_address0,
        secondMatrix_ce0,
        secondMatrix_q0,
        secondMatrix_address1,
        secondMatrix_ce1,
        secondMatrix_q1,
        result_address0,
        result_ce0,
        result_we0,
        result_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;

output  [3:0] firstMatrix_address0;
output   firstMatrix_ce0;
input  [31:0] firstMatrix_q0;

output  [3:0] firstMatrix_address1;
output   firstMatrix_ce1;
input  [31:0] firstMatrix_q1;

output  [2:0] secondMatrix_address0;
output   secondMatrix_ce0;
input  [31:0] secondMatrix_q0;

output  [2:0] secondMatrix_address1;
output   secondMatrix_ce1;
input  [31:0] secondMatrix_q1;

output  [2:0] result_address0;
output   result_ce0;
output   result_we0;
output  [31:0] result_d0;

reg ap_idle;
reg[3:0] firstMatrix_address0;
reg firstMatrix_ce0;
reg[3:0] firstMatrix_address1;
reg firstMatrix_ce1;
reg[2:0] secondMatrix_address0;
reg secondMatrix_ce0;
reg[2:0] secondMatrix_address1;
reg secondMatrix_ce1;
reg result_ce0;
reg result_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state4_pp0_stage1_iter1;
wire    ap_block_state6_pp0_stage1_iter2;
wire    ap_block_state8_pp0_stage1_iter3;
wire    ap_block_state10_pp0_stage1_iter4;
wire    ap_block_state12_pp0_stage1_iter5;
wire    ap_block_state14_pp0_stage1_iter6;
wire    ap_block_state16_pp0_stage1_iter7;
wire    ap_block_state18_pp0_stage1_iter8;
wire    ap_block_state20_pp0_stage1_iter9;
wire    ap_block_pp0_stage1_subdone;
reg   [0:0] icmp_ln6_reg_495;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] icmp_ln6_fu_225_p2;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state9_pp0_stage0_iter4;
wire    ap_block_state11_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
wire    ap_block_state15_pp0_stage0_iter7;
wire    ap_block_state17_pp0_stage0_iter8;
wire    ap_block_state19_pp0_stage0_iter9;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] select_ln6_fu_252_p3;
reg   [1:0] select_ln6_reg_499;
wire   [3:0] select_ln6_7_fu_316_p3;
reg   [3:0] select_ln6_7_reg_515;
wire   [3:0] select_ln6_8_fu_324_p3;
reg   [3:0] select_ln6_8_reg_520;
wire   [2:0] add_ln8_fu_352_p2;
reg   [2:0] add_ln8_reg_535;
reg   [2:0] add_ln8_reg_535_pp0_iter1_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter2_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter3_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter4_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter5_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter6_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter7_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter8_reg;
reg   [2:0] add_ln8_reg_535_pp0_iter9_reg;
wire   [31:0] bitcast_ln6_fu_379_p1;
wire    ap_block_pp0_stage1_11001;
wire   [31:0] bitcast_ln6_1_fu_384_p1;
wire   [31:0] bitcast_ln10_1_fu_435_p1;
wire   [31:0] bitcast_ln10_2_fu_440_p1;
wire   [31:0] bitcast_ln6_2_fu_445_p1;
wire   [31:0] bitcast_ln6_3_fu_450_p1;
wire   [31:0] grp_fu_188_p2;
reg   [31:0] mul_reg_590;
wire   [31:0] grp_fu_192_p2;
reg   [31:0] mul_1_reg_595;
reg   [31:0] mul_1_reg_595_pp0_iter2_reg;
reg   [31:0] mul_1_reg_595_pp0_iter3_reg;
wire   [31:0] bitcast_ln10_3_fu_455_p1;
wire   [31:0] bitcast_ln10_4_fu_460_p1;
reg   [31:0] mul_2_reg_610;
reg   [31:0] mul_2_reg_610_pp0_iter2_reg;
reg   [31:0] mul_2_reg_610_pp0_iter3_reg;
reg   [31:0] mul_2_reg_610_pp0_iter4_reg;
reg   [31:0] mul_2_reg_610_pp0_iter5_reg;
reg   [31:0] mul_3_reg_615;
reg   [31:0] mul_3_reg_615_pp0_iter2_reg;
reg   [31:0] mul_3_reg_615_pp0_iter3_reg;
reg   [31:0] mul_3_reg_615_pp0_iter4_reg;
reg   [31:0] mul_3_reg_615_pp0_iter5_reg;
reg   [31:0] mul_3_reg_615_pp0_iter6_reg;
reg   [31:0] mul_3_reg_615_pp0_iter7_reg;
wire   [31:0] grp_fu_179_p2;
reg   [31:0] add_reg_620;
wire   [31:0] grp_fu_184_p2;
reg   [31:0] add_1_reg_625;
reg   [31:0] add_2_reg_630;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [63:0] zext_ln6_fu_292_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln10_fu_311_p1;
wire   [63:0] j_cast_fu_332_p1;
wire   [63:0] zext_ln10_4_fu_347_p1;
wire   [63:0] zext_ln10_1_fu_394_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln10_2_fu_404_p1;
wire   [63:0] zext_ln10_5_fu_416_p1;
wire   [63:0] zext_ln10_6_fu_430_p1;
wire   [63:0] zext_ln8_fu_465_p1;
reg   [1:0] j_fu_72;
wire   [1:0] add_ln7_fu_358_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [1:0] i_fu_76;
wire   [1:0] select_ln6_1_fu_268_p3;
reg   [1:0] ap_sig_allocacmp_i_1;
reg   [2:0] indvar_flatten_fu_80;
wire   [2:0] add_ln6_1_fu_231_p2;
reg   [2:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] grp_fu_179_p0;
reg   [31:0] grp_fu_179_p1;
reg   [31:0] grp_fu_184_p0;
reg   [31:0] grp_fu_184_p1;
reg   [31:0] grp_fu_188_p0;
reg   [31:0] grp_fu_188_p1;
reg   [31:0] grp_fu_192_p0;
reg   [31:0] grp_fu_192_p1;
wire   [0:0] icmp_ln7_fu_246_p2;
wire   [1:0] add_ln6_fu_240_p2;
wire   [3:0] tmp_4_fu_260_p3;
wire   [3:0] tmp_fu_217_p3;
wire   [3:0] select_ln6_2_fu_284_p3;
wire   [3:0] select_ln6_6_fu_297_p3;
wire   [3:0] or_ln6_fu_305_p2;
wire   [2:0] zext_ln10_3_fu_337_p1;
wire   [2:0] add_ln10_fu_341_p2;
wire   [2:0] tmp_8_fu_276_p3;
wire   [3:0] or_ln6_1_fu_389_p2;
wire   [3:0] or_ln6_2_fu_399_p2;
wire   [2:0] tmp_9_cast_fu_409_p3;
wire   [1:0] xor_ln10_fu_421_p2;
wire  signed [2:0] sext_ln10_fu_426_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to9;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_277;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrix33_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_179_p0),
    .din1(grp_fu_179_p1),
    .ce(1'b1),
    .dout(grp_fu_179_p2)
);

matrix33_fadd_32ns_32ns_32_4_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_full_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_184_p0),
    .din1(grp_fu_184_p1),
    .ce(1'b1),
    .dout(grp_fu_184_p2)
);

matrix33_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_188_p0),
    .din1(grp_fu_188_p1),
    .ce(1'b1),
    .dout(grp_fu_188_p2)
);

matrix33_fmul_32ns_32ns_32_2_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_2_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_192_p0),
    .din1(grp_fu_192_p1),
    .ce(1'b1),
    .dout(grp_fu_192_p2)
);

matrix33_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_277)) begin
        if ((icmp_ln6_fu_225_p2 == 1'd0)) begin
            i_fu_76 <= select_ln6_1_fu_268_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_277)) begin
        if ((icmp_ln6_fu_225_p2 == 1'd0)) begin
            indvar_flatten_fu_80 <= add_ln6_1_fu_231_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_80 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_277)) begin
        if ((icmp_ln6_fu_225_p2 == 1'd0)) begin
            j_fu_72 <= add_ln7_fu_358_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_72 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_1_reg_625 <= grp_fu_184_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_2_reg_630 <= grp_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln6_fu_225_p2 == 1'd0))) begin
        add_ln8_reg_535 <= add_ln8_fu_352_p2;
        select_ln6_7_reg_515[3 : 2] <= select_ln6_7_fu_316_p3[3 : 2];
        select_ln6_8_reg_520[3 : 2] <= select_ln6_8_fu_324_p3[3 : 2];
        select_ln6_reg_499 <= select_ln6_fu_252_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln8_reg_535_pp0_iter1_reg <= add_ln8_reg_535;
        add_ln8_reg_535_pp0_iter2_reg <= add_ln8_reg_535_pp0_iter1_reg;
        add_ln8_reg_535_pp0_iter3_reg <= add_ln8_reg_535_pp0_iter2_reg;
        add_ln8_reg_535_pp0_iter4_reg <= add_ln8_reg_535_pp0_iter3_reg;
        add_ln8_reg_535_pp0_iter5_reg <= add_ln8_reg_535_pp0_iter4_reg;
        add_ln8_reg_535_pp0_iter6_reg <= add_ln8_reg_535_pp0_iter5_reg;
        add_ln8_reg_535_pp0_iter7_reg <= add_ln8_reg_535_pp0_iter6_reg;
        add_ln8_reg_535_pp0_iter8_reg <= add_ln8_reg_535_pp0_iter7_reg;
        add_ln8_reg_535_pp0_iter9_reg <= add_ln8_reg_535_pp0_iter8_reg;
        icmp_ln6_reg_495 <= icmp_ln6_fu_225_p2;
        mul_1_reg_595_pp0_iter2_reg <= mul_1_reg_595;
        mul_1_reg_595_pp0_iter3_reg <= mul_1_reg_595_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_reg_620 <= grp_fu_179_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        mul_2_reg_610_pp0_iter2_reg <= mul_2_reg_610;
        mul_2_reg_610_pp0_iter3_reg <= mul_2_reg_610_pp0_iter2_reg;
        mul_2_reg_610_pp0_iter4_reg <= mul_2_reg_610_pp0_iter3_reg;
        mul_2_reg_610_pp0_iter5_reg <= mul_2_reg_610_pp0_iter4_reg;
        mul_3_reg_615_pp0_iter2_reg <= mul_3_reg_615;
        mul_3_reg_615_pp0_iter3_reg <= mul_3_reg_615_pp0_iter2_reg;
        mul_3_reg_615_pp0_iter4_reg <= mul_3_reg_615_pp0_iter3_reg;
        mul_3_reg_615_pp0_iter5_reg <= mul_3_reg_615_pp0_iter4_reg;
        mul_3_reg_615_pp0_iter6_reg <= mul_3_reg_615_pp0_iter5_reg;
        mul_3_reg_615_pp0_iter7_reg <= mul_3_reg_615_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_1_reg_595 <= grp_fu_192_p2;
        mul_reg_590 <= grp_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_2_reg_610 <= grp_fu_188_p2;
        mul_3_reg_615 <= grp_fu_192_p2;
    end
end

always @ (*) begin
    if (((icmp_ln6_reg_495 == 1'd1) & (1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to9 = 1'b1;
    end else begin
        ap_idle_pp0_1to9 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_76;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 3'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_72;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            firstMatrix_address0 = zext_ln10_2_fu_404_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            firstMatrix_address0 = zext_ln10_fu_311_p1;
        end else begin
            firstMatrix_address0 = 'bx;
        end
    end else begin
        firstMatrix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            firstMatrix_address1 = zext_ln10_1_fu_394_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            firstMatrix_address1 = zext_ln6_fu_292_p1;
        end else begin
            firstMatrix_address1 = 'bx;
        end
    end else begin
        firstMatrix_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        firstMatrix_ce0 = 1'b1;
    end else begin
        firstMatrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        firstMatrix_ce1 = 1'b1;
    end else begin
        firstMatrix_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_179_p0 = add_1_reg_625;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_179_p0 = mul_reg_590;
    end else begin
        grp_fu_179_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_179_p1 = mul_2_reg_610_pp0_iter5_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_179_p1 = 32'd0;
    end else begin
        grp_fu_179_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_184_p0 = add_2_reg_630;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_184_p0 = add_reg_620;
    end else begin
        grp_fu_184_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_184_p1 = mul_3_reg_615_pp0_iter7_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_184_p1 = mul_1_reg_595_pp0_iter3_reg;
    end else begin
        grp_fu_184_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_188_p0 = bitcast_ln6_2_fu_445_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_188_p0 = bitcast_ln6_fu_379_p1;
    end else begin
        grp_fu_188_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_188_p1 = bitcast_ln10_3_fu_455_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_188_p1 = bitcast_ln10_1_fu_435_p1;
    end else begin
        grp_fu_188_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_192_p0 = bitcast_ln6_3_fu_450_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_192_p0 = bitcast_ln6_1_fu_384_p1;
    end else begin
        grp_fu_192_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_192_p1 = bitcast_ln10_4_fu_460_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_192_p1 = bitcast_ln10_2_fu_440_p1;
    end else begin
        grp_fu_192_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            secondMatrix_address0 = zext_ln10_6_fu_430_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            secondMatrix_address0 = zext_ln10_4_fu_347_p1;
        end else begin
            secondMatrix_address0 = 'bx;
        end
    end else begin
        secondMatrix_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            secondMatrix_address1 = zext_ln10_5_fu_416_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            secondMatrix_address1 = j_cast_fu_332_p1;
        end else begin
            secondMatrix_address1 = 'bx;
        end
    end else begin
        secondMatrix_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        secondMatrix_ce0 = 1'b1;
    end else begin
        secondMatrix_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        secondMatrix_ce1 = 1'b1;
    end else begin
        secondMatrix_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to9 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_341_p2 = (zext_ln10_3_fu_337_p1 + 3'd2);

assign add_ln6_1_fu_231_p2 = (ap_sig_allocacmp_indvar_flatten_load + 3'd1);

assign add_ln6_fu_240_p2 = (ap_sig_allocacmp_i_1 + 2'd1);

assign add_ln7_fu_358_p2 = (select_ln6_fu_252_p3 + 2'd1);

assign add_ln8_fu_352_p2 = (tmp_8_fu_276_p3 + zext_ln10_3_fu_337_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_277 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign bitcast_ln10_1_fu_435_p1 = secondMatrix_q1;

assign bitcast_ln10_2_fu_440_p1 = secondMatrix_q0;

assign bitcast_ln10_3_fu_455_p1 = secondMatrix_q1;

assign bitcast_ln10_4_fu_460_p1 = secondMatrix_q0;

assign bitcast_ln6_1_fu_384_p1 = firstMatrix_q0;

assign bitcast_ln6_2_fu_445_p1 = firstMatrix_q1;

assign bitcast_ln6_3_fu_450_p1 = firstMatrix_q0;

assign bitcast_ln6_fu_379_p1 = firstMatrix_q1;

assign icmp_ln6_fu_225_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_246_p2 = ((ap_sig_allocacmp_j_load == 2'd2) ? 1'b1 : 1'b0);

assign j_cast_fu_332_p1 = select_ln6_fu_252_p3;

assign or_ln6_1_fu_389_p2 = (select_ln6_7_reg_515 | 4'd2);

assign or_ln6_2_fu_399_p2 = (select_ln6_8_reg_520 | 4'd3);

assign or_ln6_fu_305_p2 = (select_ln6_6_fu_297_p3 | 4'd1);

assign result_address0 = zext_ln8_fu_465_p1;

assign result_d0 = grp_fu_184_p2;

assign select_ln6_1_fu_268_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? add_ln6_fu_240_p2 : ap_sig_allocacmp_i_1);

assign select_ln6_2_fu_284_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? tmp_4_fu_260_p3 : tmp_fu_217_p3);

assign select_ln6_6_fu_297_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? tmp_4_fu_260_p3 : tmp_fu_217_p3);

assign select_ln6_7_fu_316_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? tmp_4_fu_260_p3 : tmp_fu_217_p3);

assign select_ln6_8_fu_324_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? tmp_4_fu_260_p3 : tmp_fu_217_p3);

assign select_ln6_fu_252_p3 = ((icmp_ln7_fu_246_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign sext_ln10_fu_426_p1 = $signed(xor_ln10_fu_421_p2);

assign tmp_4_fu_260_p3 = {{add_ln6_fu_240_p2}, {2'd0}};

assign tmp_8_fu_276_p3 = {{select_ln6_1_fu_268_p3}, {1'd0}};

assign tmp_9_cast_fu_409_p3 = {{1'd1}, {select_ln6_reg_499}};

assign tmp_fu_217_p3 = {{ap_sig_allocacmp_i_1}, {2'd0}};

assign xor_ln10_fu_421_p2 = (select_ln6_reg_499 ^ 2'd2);

assign zext_ln10_1_fu_394_p1 = or_ln6_1_fu_389_p2;

assign zext_ln10_2_fu_404_p1 = or_ln6_2_fu_399_p2;

assign zext_ln10_3_fu_337_p1 = select_ln6_fu_252_p3;

assign zext_ln10_4_fu_347_p1 = add_ln10_fu_341_p2;

assign zext_ln10_5_fu_416_p1 = tmp_9_cast_fu_409_p3;

assign zext_ln10_6_fu_430_p1 = $unsigned(sext_ln10_fu_426_p1);

assign zext_ln10_fu_311_p1 = or_ln6_fu_305_p2;

assign zext_ln6_fu_292_p1 = select_ln6_2_fu_284_p3;

assign zext_ln8_fu_465_p1 = add_ln8_reg_535_pp0_iter9_reg;

always @ (posedge ap_clk) begin
    select_ln6_7_reg_515[1:0] <= 2'b00;
    select_ln6_8_reg_520[1:0] <= 2'b00;
end

endmodule //matrix33
