# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SoC/SoC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC || ORIG_REF_NAME==SoC} -quiet] -quiet

# IP: bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SoC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_AXI_Manager_0_0/SoC_AXI_Manager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_AXI_Manager_0_0 || ORIG_REF_NAME==SoC_AXI_Manager_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_axi_smc_0/SoC_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_axi_smc_0 || ORIG_REF_NAME==SoC_axi_smc_0} -quiet] -quiet

# Block Designs: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/bd_d7be.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_0/bd_d7be_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_2/bd_d7be_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_3/bd_d7be_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_4/bd_d7be_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/bd_d7be_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/bd_d7be_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_7/bd_d7be_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_8/bd_d7be_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_9/bd_d7be_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/bd_d7be_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/bd_d7be_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_12/bd_d7be_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_13/bd_d7be_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_14/bd_d7be_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_15/bd_d7be_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_16/bd_d7be_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_17/bd_d7be_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_18/bd_d7be_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_19/bd_d7be_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_20/bd_d7be_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_21/bd_d7be_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_22/bd_d7be_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_23/bd_d7be_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_24/bd_d7be_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_25/bd_d7be_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_26/bd_d7be_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_27/bd_d7be_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_28/bd_d7be_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_29/bd_d7be_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_30/bd_d7be_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_31/bd_d7be_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SoC_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/bd_d7be_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_2/bd_d7be_arsw_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_3/bd_d7be_rsw_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_4/bd_d7be_awsw_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/bd_d7be_wsw_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/bd_d7be_bsw_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/bd_d7be_s00a2s_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/bd_d7be_sarn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_12/bd_d7be_srn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_13/bd_d7be_sawn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_14/bd_d7be_swn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_15/bd_d7be_sbn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_19/bd_d7be_s01a2s_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_20/bd_d7be_sarn_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_21/bd_d7be_srn_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_22/bd_d7be_sawn_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_23/bd_d7be_swn_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_24/bd_d7be_sbn_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_25/bd_d7be_m00s2a_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_26/bd_d7be_m00arn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_27/bd_d7be_m00rn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_28/bd_d7be_m00awn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_29/bd_d7be_m00wn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_30/bd_d7be_m00bn_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/ooc.xdc

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/SoC_1_1/SoC_1_1.gen/sources_1/bd/SoC/SoC_ooc.xdc
