@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Mar 03 14:43:30 +0700 2025
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim blk_mem_gen_0_behav -key {Behavioral:sim_1:Functional:blk_mem_gen_0} -tclbatch blk_mem_gen_0.tcl -log simulate.log"
call xsim  blk_mem_gen_0_behav -key {Behavioral:sim_1:Functional:blk_mem_gen_0} -tclbatch blk_mem_gen_0.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
