# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/test/test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test || ORIG_REF_NAME==test} -quiet] -quiet

# IP: bd/test/ip/test_zynq_ultra_ps_e_0_0/test_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==test_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/test/ip/test_Compute_0_0/test_Compute_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_Compute_0_0 || ORIG_REF_NAME==test_Compute_0_0} -quiet] -quiet

# IP: bd/test/ip/test_xbar_0/test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_xbar_0 || ORIG_REF_NAME==test_xbar_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_ds_0/test_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_auto_ds_0 || ORIG_REF_NAME==test_auto_ds_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_0/test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_auto_pc_0 || ORIG_REF_NAME==test_auto_pc_0} -quiet] -quiet

# IP: bd/test/ip/test_auto_ds_1/test_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_auto_ds_1 || ORIG_REF_NAME==test_auto_ds_1} -quiet] -quiet

# IP: bd/test/ip/test_auto_pc_1/test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_auto_pc_1 || ORIG_REF_NAME==test_auto_pc_1} -quiet] -quiet

# IP: bd/test/ip/test_ps8_0_axi_periph_0/test_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_ps8_0_axi_periph_0 || ORIG_REF_NAME==test_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/test/ip/test_rst_ps8_0_99M_0/test_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==test_rst_ps8_0_99M_0 || ORIG_REF_NAME==test_rst_ps8_0_99M_0} -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_zynq_ultra_ps_e_0_0/test_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_zynq_ultra_ps_e_0_0/test_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==test_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_ds_0/test_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_auto_ds_0 || ORIG_REF_NAME==test_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_ds_0/test_auto_ds_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_pc_0/test_auto_pc_0_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_ds_1/test_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_auto_ds_1 || ORIG_REF_NAME==test_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_ds_1/test_auto_ds_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_auto_pc_1/test_auto_pc_1_ooc.xdc

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_rst_ps8_0_99M_0/test_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_rst_ps8_0_99M_0 || ORIG_REF_NAME==test_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/ip/test_rst_ps8_0_99M_0/test_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_rst_ps8_0_99M_0 || ORIG_REF_NAME==test_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/Repository/Vivado/SoC/Hw3_remake/Hw3_remake.gen/sources_1/bd/test/test_ooc.xdc
